const WASD = [
  [
    "           XXXXXXXXX            ",
    "           X       XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X XXXXX XX           ",
    "           X       XX           ",
    "           XXXXXXXXXX           ",
    "            XXXXXXXXX           ",
    "                                ",
    "XXXXXXXXX  XXXXXXXXX  XXXXXXXXX ",
    "X       XX X       XX X       XX",
    "X   X   XX X  XXXX XX X XXXX  XX",
    "X  X X  XX X X     XX X X   X XX",
    "X X   X XX X  XXX  XX X X   X XX",
    "X XXXXX XX X     X XX X X   X XX",
    "X X   X XX X XXXX  XX X XXXX  XX",
    "X       XX X       XX X       XX",
    "XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX",
    " XXXXXXXXX  XXXXXXXXX  XXXXXXXXX",
  ],
  [
    "                                ",
    "            XXXXXXXXX            ",
    "            X       X           ",
    "            X X X X X           ",
    "            X X X X X           ",
    "            X X X X X           ",
    "            X X X X X           ",
    "            X XXXXX X           ",
    "            X       X           ",
    "            XXXXXXXXX           ",
    "                                ",
    "XXXXXXXXX  XXXXXXXXX  XXXXXXXXX ",
    "X       XX X       XX X       XX",
    "X   X   XX X  XXXX XX X XXXX  XX",
    "X  X X  XX X X     XX X X   X XX",
    "X X   X XX X  XXX  XX X X   X XX",
    "X XXXXX XX X     X XX X X   X XX",
    "X X   X XX X XXXX  XX X XXXX  XX",
    "X       XX X       XX X       XX",
    "XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX",
    " XXXXXXXXX  XXXXXXXXX  XXXXXXXXX",
  ],
  [
    "           XXXXXXXXX            ",
    "           X       XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X XXXXX XX           ",
    "           X       XX           ",
    "           XXXXXXXXXX           ",
    "            XXXXXXXXX           ",
    "                                ",
    "           XXXXXXXXX  XXXXXXXXX ",
    " XXXXXXXXX X       XX X       XX",
    " X       X X  XXXX XX X XXXX  XX",
    " X   X   X X X     XX X X   X XX",
    " X  X X  X X  XXX  XX X X   X XX",
    " X X   X X X     X XX X X   X XX",
    " X XXXXX X X XXXX  XX X XXXX  XX",
    " X X   X X X       XX X       XX",
    " X       X XXXXXXXXXX XXXXXXXXXX",
    " XXXXXXXXX  XXXXXXXXX  XXXXXXXXX",
  ],
  [
    "           XXXXXXXXX            ",
    "           X       XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X XXXXX XX           ",
    "           X       XX           ",
    "           XXXXXXXXXX           ",
    "            XXXXXXXXX           ",
    "                                ",
    "XXXXXXXXX             XXXXXXXXX ",
    "X       XX  XXXXXXXXX X       XX",
    "X   X   XX  X       X X XXXX  XX",
    "X  X X  XX  X  XXXX X X X   X XX",
    "X X   X XX  X X     X X X   X XX",
    "X XXXXX XX  X  XXX  X X X   X XX",
    "X X   X XX  X     X X X XXXX  XX",
    "X       XX  X XXXX  X X       XX",
    "XXXXXXXXXX  X       X XXXXXXXXXX",
    " XXXXXXXXX  XXXXXXXXX  XXXXXXXXX",
  ],
  [
    "           XXXXXXXXX            ",
    "           X       XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X X X X XX           ",
    "           X XXXXX XX           ",
    "           X       XX           ",
    "           XXXXXXXXXX           ",
    "            XXXXXXXXX           ",
    "                                ",
    "XXXXXXXXX  XXXXXXXXX            ",
    "X       XX X       XX  XXXXXXXXX",
    "X   X   XX X  XXXX XX  X       X",
    "X  X X  XX X X     XX  X XXXX  X",
    "X X   X XX X  XXX  XX  X X   X X",
    "X XXXXX XX X     X XX  X X   X X",
    "X X   X XX X XXXX  XX  X X   X X",
    "X       XX X       XX  X XXXX  X",
    "XXXXXXXXXX XXXXXXXXXX  X       X",
    " XXXXXXXXX  XXXXXXXXX  XXXXXXXXX",
  ],
];

const MOVE_TXT = [
  [
    " X X   XXX  X   X XXX",
    "X X X X   X X   X X  ",
    "X X X X   X  X X  XXX",
    "X X X X   X  X X  X  ",
    "X X X  XXX    X   XXX",
  ],
];

const SPACE = [
  [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "X                             XX",
    "X   XXXX XXX    X    XXX XXX  XX",
    "X  X     X  X  X X  X    X    XX",
    "X   XXX  X  X X   X X    XXX  XX",
    "X      X XXX  XXXXX X    X    XX",
    "X  XXXX  X    X   X  XXX XXX  XX",
    "X                             XX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                               ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    " X                             X",
    " X   XXXX XXX    X    XXX XXX  X",
    " X  X     X  X  X X  X    X    X",
    " X   XXX  X  X X   X X    XXX  X",
    " X      X XXX  XXXXX X    X    X",
    " X  XXXX  X    X   X  XXX XXX  X",
    " X                             X",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
];

const SHOOT_TXT = [
  [
    " XXXX X   X  XXX   XXX  XXXXX",
    "X     X   X X   X X   X   X  ",
    " XXX  XXXXX X   X X   X   X  ",
    "    X X   X X   X X   X   X  ",
    "XXXX  X   X  XXX   XXX    X  ",
  ],
];

export default {
  WASD,
  MOVE_TXT,
  SPACE,
  SHOOT_TXT,
};
