const LIGHTED = [
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "              X",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "             X",
    "              X",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            X",
    "             X",
    "",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "           X",
    "            X",
    "",
    "              X",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "             X",
    "              X",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            X",
    "             X",
    "              X",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            X",
    "             X",
    "",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            X",
    "",
    "",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
    "              XX",
  ],
];

const EXPLODE = [
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "              XXX          ",
    "            XXXXX          ",
    "            XXXXXX         ",
    "            XXXXXX         ",
    "            XXXXXX         ",
    "            XXXXX          ",
    "                           ",
    "                           ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "              XXX",
    "           XXXXXXXX",
    "          XXXXXXXXXX",
    "          XXXXXXXXXXX",
    "          XXXXXXXXXXX",
    "          XXXXXXXXXXX",
    "           XXXXXXXXXX",
    "           XXXXXXXXXX",
    "           XXXXXXXXXX",
    "            XXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "           XXXXXXXX",
    "          XXXXXXXXXXX",
    "         XXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXXX",
    "         XXXXXXXXXXXXXXXX",
    "         XXXXXXXXXXXXXXXX",
    "          XXXXXXXXXXXXXX",
    "            XXXXXXXXXXX",
  ],
  [
    "",
    "",
    "            XXXXXXXX",
    "         XXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX  XXXXXXXXXXXX",
    "XXXXXXXXXXXX    XXXXXXXXXXXX",
    " XXXXXXXXXXX    XXXXXXXXXXXX",
    " XXXXXXXXXXX   XXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXX",
  ],
  [
    "      XXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX    XXXXXXXXXXXXX",
    "XXXXXXXXXXXX      XXXXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXXX",
    " XXXXXXXXXX        XXXXXXXXXXX",
    " XXXXXXXXXXX       XXXXXXXXXXX",
    "  XXXXXXXXXX       XXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXX",
  ],
  [
    "      XXXX   XXXXX  XX XX",
    "     XXXXXX XXXXXXX X XXXX",
    "    XXXXXXX XXXXXXX   XXXXXX",
    "   XXXXXXXX XXXXXXX  XXXXXXX",
    "  XXXXXXXXX XXXXXXX  XXXXXXX",
    "  XXXXXXXXX XXXXXX  XXXXXXX",
    "  XXXXXXXX  XXXXXX  XXXXXX X",
    "   XXXXXX          XXXXXXX",
    "     XXXX          XXXXX",
    "                    XXX",
    "  XXXXX",
    "XXXXXXX            XXXXXXXXX",
    " XXXXXX            XXXXXXXXXX",
    " XXXXXXX           XXXXXXXXXXX",
    "  XXXXXXX         XXXXXXXXXXXX",
    "   XXXXXXXX     XXXXXXXXXXXXXX",
    "    XXXXXXXXXXX XXXXXXXXXXXXXX",
    "     XXXXXXXXXX XXXXXXXXXX",
    "      XXXXXXXXX XXXXXXXXX",
    "        XXXXXXX XXXXXXXX",
  ],
  [
    "             XXX       XX",
    "     XXX    XXXXXX    XX",
    "    XXXX    XXXXXX    XXX  X",
    "   XXXXXX   XXXXXXX   XXXX X",
    "   XXXXXX   XXXXXX    XXXX X",
    "  XXXXXX    XXXXX    XXXXX",
    " XXXXXXX             XXXXX X",
    "  XXXXXX           X XXXX",
    "    XXX            X",
    "                    XXX",
    "  XXX",
    "XXXXXX             XX",
    "XXXXXX                XXXX",
    "XXXXX              X XXXXXXX",
    " XXX   XX            XXXXXXX",
    "     XXXXXX      XXX XXXXXXX",
    "     XXXXXXXX    XXX  XXXXXX",
    "    XXXXXXXX     XXXXX",
    "     XXXXXXXX    XXXXXXX",
    "                 XXXXXX",
  ],
  [
    "              X        XX",
    "     XX     XX XXX    X",
    "    XX                X X",
    "   X                   X X",
    "   X                   X X X",
    "  XX                    XX",
    " X X                     X X",
    "  X                X X",
    "",
    "                    X X",
    "",
    "X   X              XX",
    "X",
    "X                  X X     X",
    " XX    XX                X X",
    "          X",
    "     XX                X  X",
    "         XXX     X",
    "     XXXX   X    X    XX",
    "                  XXXX",
  ],
];

export default {
  LIGHTED,
  EXPLODE,
};
