const STAND = [
  [
    "      XX             ",
    "     X  X  XX        ",
    "   XXXXXXXXXXXXXXX   ",
    "   XXXXXXXXXX        ",
    "   XX   X X          ",
    "       X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
];

const SHOOT = [
  [
    "      XX            X",
    "     X  X  XX      X ",
    "   XXXXXXXXXXXXXXX   ",
    "   XXXXXXXXXX      X ",
    "   XX   X X         X",
    "       X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
  [
    "      XX   XX        ",
    "     X  XXXXXXXXX    ",
    "   XXXXXXXXXX        ",
    "   XXXXXXXXXX        ",
    "   XX   X X          ",
    "       X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
  [
    "      XX             ",
    "     X  X  XX        ",
    "   XXXXXXXXXXXXXXX   ",
    "   XXXXXXXXXX        ",
    "   XX   X X          ",
    "       X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
  [
    "                     ",
    "      XX   XX        ",
    "     X  XXXXXXXXXX   ",
    "   XXXXXXXXXX        ",
    "   XXXX X X          ",
    "   XX  X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
  [
    "      XX             ",
    "     X  X  XX        ",
    "   XXXXXXXXXXXXXXX   ",
    "   XXXXXXXXXX        ",
    "   XX   X X          ",
    "       X   X         ",
    "       X   X         ",
    "      X     X        ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
];

const BROKE = [
  [
    "     XXX XX          ",
    "    XXXXXX X         ",
    "    XXXXXXX X        ",
    "        XXXXX        ",
    "        X XXX        ",
    "       X   X XX      ",
    "       X   X   XX    ",
    "      X     X    X   ",
    "      X     X        ",
    "     X       X       ",
    "    X         X      ",
  ],
];

export default {
  STAND,
  SHOOT,
  BROKE,
};
