const GLIDE = [
  [
    "       XXXXXXXXX       ",
    "     XXXOXOXOXOXXX     ",
    "   XXXOXOXOXOXOXOXXX   ",
    "  XXOXOXOXOXOXOXOXOXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "X                     X",
    " X                   X ",
    " X   XX         XX   X ",
    "  X  XXXX     XXXX  X  ",
    "  X   XXXXXXXXXXX   X  ",
    "   X    XXXXXXX    X   ",
    "   X     XXXXX     X   ",
    "    X   XXXXXXX   X    ",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "       XXXXXXXXX       ",
    "     XXXOXOXOXOXXX     ",
    "   XXXOXOXOXOXOXOXXX   ",
    "  XXOXOXOXOXOXOXOXOXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "X                     X",
    "XX                   XX",
    " X   XX         XX   X ",
    " XX  XXXX     XXXX  XX ",
    "  X   XXXXXXXXXXX   X  ",
    "  XX    XXXXXXX    XX  ",
    "   X     XXXXX     X   ",
    "   XX   XXXXXXX   XX   ",
    "    X  XXXXXXXXX  X    ",
    "    XXXXXOXXXOXXXXX    ",
    "     XXXOOOXOOOXXX     ",
    "     XXXOOXXXOOXXX     ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
];

const FALL = [
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "     XX         XX     ",
    "     XXXX     XXXX     ",
    "      XXXXXXXXXXX      ",
    "        XXXXXXX        ",
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXXX       ",
    "      XXXOXXXOXXX      ",
    "      XXOOOXOOOXX      ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
];

const EXPLODE = [
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "              XXX          ",
    "            XXXXX          ",
    "            XXXXXX         ",
    "            XXXXXX         ",
    "            XXXXXX         ",
    "            XXXXX          ",
    "                           ",
    "                           ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "              XXX",
    "           XXXXXXXX",
    "          XXXXXXXXXX",
    "          XXXXXXXXXXX",
    "          XXXXXXXXXXX",
    "          XXXXXXXXXXX",
    "           XXXXXXXXXX",
    "           XXXXXXXXXX",
    "           XXXXXXXXXX",
    "            XXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "           XXXXXXXX",
    "          XXXXXXXXXXX",
    "         XXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXXX",
    "         XXXXXXXXXXXXXXXX",
    "         XXXXXXXXXXXXXXXX",
    "          XXXXXXXXXXXXXX",
    "            XXXXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            XXXXXXXX",
    "         XXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX  XXXXXXXXXXXX",
    "XXXXXXXXXXXX    XXXXXXXXXXXX",
    " XXXXXXXXXXX    XXXXXXXXXXXX",
    " XXXXXXXXXXX   XXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "      XXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXX    XXXXXXXXXXXXX",
    "XXXXXXXXXXXX      XXXXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXX",
    "XXXXXXXXXXX        XXXXXXXXXXX",
    " XXXXXXXXXX        XXXXXXXXXXX",
    " XXXXXXXXXXX       XXXXXXXXXXX",
    "  XXXXXXXXXX       XXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "    XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "     XXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "      XXXX   XXXXX  XX XX",
    "     XXXXXX XXXXXXX X XXXX",
    "    XXXXXXX XXXXXXX   XXXXXX",
    "   XXXXXXXX XXXXXXX  XXXXXXX",
    "  XXXXXXXXX XXXXXXX  XXXXXXX",
    "  XXXXXXXXX XXXXXX  XXXXXXX",
    "  XXXXXXXX  XXXXXX  XXXXXX X",
    "   XXXXXX          XXXXXXX",
    "     XXXX          XXXXX",
    "                    XXX",
    "  XXXXX",
    "XXXXXXX            XXXXXXXXX",
    " XXXXXX            XXXXXXXXXX",
    " XXXXXXX           XXXXXXXXXXX",
    "  XXXXXXX         XXXXXXXXXXXX",
    "   XXXXXXXX     XXXXXXXXXXXXXX",
    "    XXXXXXXXXXX XXXXXXXXXXXXXX",
    "     XXXXXXXXXX XXXXXXXXXX",
    "      XXXXXXXXX XXXXXXXXX",
    "        XXXXXXX XXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "             XXX       XX",
    "     XXX    XXXXXX    XX",
    "    XXXX    XXXXXX    XXX  X",
    "   XXXXXX   XXXXXXX   XXXX X",
    "   XXXXXX   XXXXXX    XXXX X",
    "  XXXXXX    XXXXX    XXXXX",
    " XXXXXXX             XXXXX X",
    "  XXXXXX           X XXXX",
    "    XXX            X",
    "                    XXX",
    "  XXX",
    "XXXXXX             XX",
    "XXXXXX                XXXX",
    "XXXXX              X XXXXXXX",
    " XXX   XX            XXXXXXX",
    "     XXXXXX      XXX XXXXXXX",
    "     XXXXXXXX    XXX  XXXXXX",
    "    XXXXXXXX     XXXXX",
    "     XXXXXXXX    XXXXXXX",
    "                 XXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "              X        XX",
    "     XX     XX XXX    X",
    "    XX                X X",
    "   X                   X X",
    "   X                   X X X",
    "  XX                    XX",
    " X X                     X X",
    "  X                X X",
    "",
    "                    X X",
    "",
    "X   X              XX",
    "X",
    "X                  X X     X",
    " XX    XX                X X",
    "          X",
    "     XX                X  X",
    "         XXX     X",
    "     XXXX   X    X    XX",
    "                  XXXX",
  ],
  [],
];

const BURY = [
  [
    "       XXXXXXXXX       ",
    "     XXXOXOXOXOXXX     ",
    "   XXXOXOXOXOXOXOXXX   ",
    "  XXOXOXOXOXOXOXOXOXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "X                     X",
    " X                   X ",
    " X   XX         XX   X ",
    "  X  XXXX     XXXX  X  ",
    "  X   XXXXXXXXXXX   X  ",
    "   X    XXXXXXX    X   ",
    "   X     XXXXX     X   ",
    "    X   XXXXXXX   X    ",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "       XXXXXXXXX       ",
    "     XXXOXOXOXOXXX     ",
    "   XXXOXOXOXOXOXOXXX   ",
    "  XXOXOXOXOXOXOXOXOXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    " X   XX         XX   X ",
    "  X  XXXX     XXXX  X  ",
    "  X   XXXXXXXXXXX   X  ",
    "   X    XXXXXXX    X   ",
    "   X     XXXXX     X   ",
    "    X   XXXXXXX   X    ",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "     XXXXXXXX   XX     ",
    "   XXX X X XXXXXXXXX   ",
    "  XX X X X X X X X XX  ",
    " XXX X X X X X X X XXX ",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "  X   XXXXXXXXXXX   X  ",
    "   X    XXXXXXX    X   ",
    "   X     XXXXX     X   ",
    "    X   XXXXXXX   X    ",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "     XXXXXXXX   XX     ",
    "   XXX X X XXXXXXXXX   ",
    "  XX X X X X X X X XX  ",
    " XXX X X X X X X X XXX ",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "   X     XXXXX     X   ",
    "    X   XXXXXXX   X    ",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "   XXXXXXXXX      XX   ",
    "  XX X X X XX    XXXX  ",
    " XXX X X X XXXXXXX XXX ",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "    X  XXXXXXXXX  X    ",
    "     XXXXOXXXOXXXX     ",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "   XXXXXXXXX      XX   ",
    "  XX X X X XX    XXXX  ",
    " XXX X X X XXXXXXX XXX ",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "     XXXOOOXOOOXXX     ",
    "      XXOOXXXOOXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "    XXXXXX             ",
    "   XXX X XX            ",
    "  XX X X XXX       XXXX",
    " X X X X X XXXXXXXXX XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXOXXXXX      ",
    "      XXXXXXXXXXX      ",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "    XXXXXX             ",
    "   XXX X XX            ",
    "  XX X X XXX       XXXX",
    " X X X X X XXXXXXXXX XX",
    "XX X X X X X X X X X XX",
    "XX X X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "      XXXXXOXXXXX      ",
    "      XXXXOOOXXXX      ",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "      XXXXX            ",
    "     XXX XXXX          ",
    "    XX X X XXXXX    XXX",
    "   XXX X X X X XXXXXXXX",
    "  XX X X X X X X X X XX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "       XXXOOOXXX       ",
    "        XXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "       XXX             ",
    "     XXX XXX           ",
    "   XXX X X XXX         ",
    "  XX X X X X X       XX",
    " XXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "       XXXXXXX         ",
    "     XXX X X X         ",
    "    XX X X X XXX       ",
    "  XXXXXXXXXXXXXXXXX    ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "        XXXXX          ",
    "       X X X X         ",
    "      XXXXXXXXX        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "           X           ",
    "          XXXXX        ",
  ],
];

export default {
  GLIDE,
  FALL,
  EXPLODE,
  BURY,
};
