const GLIDE = [
  [
    "       XXXXXXXXX       ",
    "     XXXXXXXXXXXXX     ",
    "   XXXXXOXOXOXOXXXXX   ",
    "  XXXXOXOXOXOXOXOXXXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXXXXXXXXXX",
    "XXOXOXOXXXXXXXX       X",
    "XXXXXXXXX             X",
    "XX                   XX",
    " XX                 XX ",
    "  XX      XXX      XX  ",
    "   XX    XXXXX    XX   ",
    "    XX   XXXXX   XX    ",
    "     XX  XXXXX  XX     ",
    "      XX  XXX  XX      ",
    "       XX  X  XX       ",
    "        XXXXXXX        ",
    "      XX  XXX  XX      ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "       XXXXXXXXX       ",
    "     XXXXXXXXXXXXX     ",
    "   XXXXXOXOXOXOXXXXX   ",
    "  XXXXOXOXOXOXOXOXXXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "X                     X",
    "XX                   XX",
    " XX                 XX ",
    "  XX      XXX      XX  ",
    "   XX    XXXXX    XX   ",
    "    XX   XXXXX   XX    ",
    "     XX  XXXXX  XX     ",
    "      XX  XXX  XX      ",
    "       XX  X  XX       ",
    "        XXXXXXX        ",
    "      XX  XXX  XX      ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "       XXXXXXXXX       ",
    "     XXXXXXXXXXXXX     ",
    "   XXXXXOXOXOXOXXXXX   ",
    "  XXXXOXOXOXOXOXOXXXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXOXOXOXOXOXOXX",
    "X       XXXXXXXXOXOXOXX",
    "X             XXXXXXXXX",
    "XX                   XX",
    " XX       XXX       XX ",
    "  XX     XXXXX     XX  ",
    "   XX    XXXXX    XX   ",
    "    XX   XXXXX   XX    ",
    "     XX   XXX   XX     ",
    "      XXX  X  XXX      ",
    "        XXXXXXX        ",
    "      XX  XXX  XX      ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "       XXXXXXXXX       ",
    "     XXXXXXXXXXXXX     ",
    "   XXXXXOXOXOXOXXXXX   ",
    "  XXXXOXOXOXOXOXOXXXX  ",
    " XXXOXOXOXOXOXOXOXOXXX ",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXOXOXOXOXOXOXOXOXOXOXX",
    "XXXXXXXXXXXXXXXXXXXXXXX",
    "X                     X",
    "XX                   XX",
    " XX       XXX       XX ",
    "  XX     XXXXX     XX  ",
    "   XX    XXXXX    XX   ",
    "    XX   XXXXX   XX    ",
    "     XX   XXX   XX     ",
    "      XXX  X  XXX      ",
    "        XXXXXXX        ",
    "      XX  XXX  XX      ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
];

const STAND = [
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "          XXX          ",
    "         XXXXX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXXXX        ",
    "      XX  XXX  XX      ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
];

const FALL = [
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "          XXX          ",
    "         XXXXX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "      XX   X   XX      ",
    "        XXXXXXX        ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
];

const SPLASH_DIE = [
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "       X",
    "      X            X",
    "       XXXX   XXXX",
    "       XX  X XXXX X",
    "        XX XXX",
    "        XXXXX X",
    "        XX X XX",
    "         XXXX X",
    "         XX XX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "    X  X        X    X",
    "   X          X     X",
    "   XXXXX  X    XXXXXX X",
    "    XXXXXX     XXXX XXXX",
    "    XX XXXXXXXXXX XXXXX",
    "   X  XXXXXXXXXXXXXX  X",
    "       XX  XXX XXX XX",
    "       XXXXXX XXX X",
    "      X XXXXXX",
    "        XX XX X X",
    "        XXXXXXX",
    "         X   XX",
    "         XXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "  X            X     XX",
    "   X    XX      XXXXXX",
    "    XXXX       XXXXXXX",
    "  XXXXXXXXXXXXXX  X XX X",
    "  X XX XXXXXX  XXXXX XX X",
    "  XXXX XX  XXXXXX XXXXX",
    " X XX X XX XXX      XX X",
    "X  X  X XXXXX X   XX  X",
    "    X   XX XXXX     X",
    "       X X XXXXX",
    "         XXXXX X",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "        X",
    " XX       X   XX  X   X",
    "  XXXXXX  XXXX     XXX",
    " XX X XXXXXX  XXXXXXXX",
    "XXXXXX   XX  XX  XX  XX",
    "X X      XX XX   XXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "         X     X   X",
    "       XX XXXXXX  X",
    "         XXX  X  X",
    "       XXXX XXXXXXXXX",
  ],
];

const SHOT_DIE = [
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "          XXX          ",
    "         XXXXX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "         XXXXX         ",
    "        X XXX X        ",
    "        X XXX X        ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "           XXX         ",
    "          XXXXX        ",
    "          XXXXX        ",
    "          XXXXX        ",
    "           XXX         ",
    "            X          ",
    "          XXXX         ",
    "         X XXX         ",
    "        X XXXX         ",
    "         X XXX         ",
    "           XXX         ",
    "           XXX         ",
    "          X  X         ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            XXX        ",
    "           XXXXX       ",
    "           XXXXX       ",
    "           XXXXX       ",
    "            XXX        ",
    "             X         ",
    "           XXXX        ",
    "          X XXX        ",
    "         X XXXX        ",
    "          X XXX        ",
    "           XX X        ",
    "          X  X         ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                 XXX   ",
    "                XXXXX  ",
    "                XXXXX  ",
    "                XXXXX  ",
    "          XXXXXXXXXX   ",
    "             XXXX      ",
    "         XXXXXXX       ",
    "           XXXX        ",
    "          X  X         ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                 XXX   ",
    "                XXXXX  ",
    "          X     XXXXX  ",
    "           X  XXXXXXX  ",
    "         X  XXXXXXXX   ",
    "          X XXXXX      ",
    "           XXXXX       ",
    "           XXXX        ",
    "          X  X         ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                 XXX   ",
    "            X   XXXXX  ",
    "             X XXXXXX  ",
    "         XX  XXXXXXXX  ",
    "           XXXXX XXX   ",
    "           XXXX        ",
    "           XXX         ",
    "          X  X         ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "            XX XX   XXX ",
    "          XXXXXXXX XXXXX",
    "         X XXXXXXXXXXXXX",
    "        X  XXXXXXX XXXXX",
    "        X X         XXX ",
    "        X  X            ",
    "        XX X            ",
    "           XX           ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
    "            XXXXXXXXXXXX",
    "        XXXXXXXXXX XXXXX",
    "       XXXXXXXXXXX  XXX ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
    "            XXXXXXXXXXXX",
    "        XXXXXXXXXX XXXXX",
    "       XXXXXXXXXXX  XXX ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
    "            XXXXXXXXXXXX",
    "        XXXXXXXXXX XXXXX",
    "       XXXXXXXXXXX  XXX ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
    "            XXXXXXXXXXXX",
    "        XXXXXXXXXX XXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
    "            XXXXXXXXXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
    "                   XXXXX",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                    XXX ",
  ],
];

const PLANT_BOMB = [
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "          XXX          ",
    "         XXXXX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX          ",
    "      XX  XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "       XXX             ",
    "      XXXXX            ",
    "      XXXXX            ",
    "      XXXXX            ",
    "       XXXX            ",
    "         XXX           ",
    "       XXXXX           ",
    "      XX XXX           ",
    "        XXXX           ",
    "      XX XXXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "       XXX             ",
    "      XXXXX            ",
    "      XXXXX            ",
    "      XXXXX            ",
    "       XXX             ",
    "        XXX            ",
    "      XXXXXX           ",
    "      X XXXX           ",
    "       XXXXXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                       ",
    "                       ",
    "      XXX              ",
    "     XXXXX             ",
    "     XXXXX             ",
    "     XXXXXX            ",
    "       XXXXX           ",
    "       XXXXX           ",
    "      X X XXX          ",
    "     X XX XXX          ",
    "       X  X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "     XXX               ",
    "    XXXXX              ",
    "    XXXXX              ",
    "    XXXXXXXX           ",
    "     XXXXXXX           ",
    "     X XXXXXX          ",
    "    X X   XXX          ",
    "     X    X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "                       ",
    "                       ",
    "      XXX              ",
    "     XXXXX             ",
    "     XXXXX             ",
    "     XXXXXX            ",
    "       XXXXX           ",
    "       XXXXX           ",
    "      X X XXX          ",
    "     X XX XXX          ",
    "       X  X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "       XXX             ",
    "      XXXXX            ",
    "      XXXXX            ",
    "      XXXXX            ",
    "       XXX             ",
    "        XXX            ",
    "      XXXXXX           ",
    "      X XXXX           ",
    "       XXXXXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "       XXX             ",
    "      XXXXX            ",
    "      XXXXX            ",
    "      XXXXX            ",
    "       XXXX            ",
    "         XXX           ",
    "       XXXXX           ",
    "      XX XXX           ",
    "        XXXX           ",
    "      XX XXXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "          XXX          ",
    "         XXXXX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX          ",
    "      XX  XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "          X X          ",
    "         XX XX         ",
  ],
];

const RUN = [
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "    XXX                ",
    "   XXXXX               ",
    "   XXXXX               ",
    "   XXXXXXXXXX          ",
    "    XXXXX              ",
    "     XXXXXXXXX         ",
    "      XXXXX            ",
    "       XXXXXX          ",
    "         XXXX          ",
    "     X  XXXXXX         ",
    "      XX      XX       ",
    "                X      ",
    "               X       ",
    "                       ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "    XXX                ",
    "   XXXXX               ",
    "   XXXXX               ",
    "   XXXXXXXXXX          ",
    "    XXXXX              ",
    "     XXXXXXXXX         ",
    "      XXXXX            ",
    "       XXXXXX          ",
    "         XXXX          ",
    "          XXX          ",
    "         X   X         ",
    "      X X     X        ",
    "       X       X       ",
    "              X        ",
  ],
  [
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "                       ",
    "    XXX                ",
    "   XXXXX               ",
    "   XXXXX               ",
    "   XXXXXXXXXX          ",
    "    XXXXX              ",
    "     XXXXXXXXX         ",
    "      XXXXX            ",
    "       XXXXXX          ",
    "         XXXX          ",
    "          XXX          ",
    "          X X          ",
    "          X X          ",
    "        X X X          ",
    "         X XX          ",
  ],
];

export default {
  GLIDE,
  STAND,
  FALL,
  SPLASH_DIE,
  SHOT_DIE,
  PLANT_BOMB,
  RUN,
};
