const DRIVE = [
  [
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXX            ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  XXXXX ",
    "    XXXXXXXXXXXXXXXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XX X ",
    "   XXXXXXXXXXXXX XX   ",
    "  XXXXXXXXXXXX X XX   ",
    " XXXXXXXXXXXXX X XXX  ",
    " XXXXXXXXXXX X X XXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXOXX",
    "  XXOX          XXXXX ",
    "   XXX          X XXX ",
  ],
  [
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXXXX          ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  XXXXX ",
    "    XXXXXXXXXXXXXXXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XX X ",
    "   XXXXXXXXXXXXX XX   ",
    "  XXXXXXXXXXXX X XX   ",
    " XXXXXXXXXXXXX X XXX  ",
    " XXXXXXXXXXX X X XXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXX ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXOXX",
    "  XXOXX         XXXXXX",
    "    XX          X  XX ",
  ],
  [
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXX            ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  XXXXX ",
    "    XXXXXXXXXXXXXXXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XX X ",
    "   XXXXXXXXXXXXX XX   ",
    "  XXXXXXXXXXXX X XX   ",
    " XXXXXXXXXXXXX X XXX  ",
    " XXXXXXXXXXX X X XXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXOXX",
    "   XOXX         XXXXXX",
    "   XXX          X XXX ",
  ],
];

const SCOOTER_BROKE = [
  [
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXXXX          ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  XXXXX ",
    "    XXXXXXXXXXXXXXXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XX X ",
    "   XXXXXXXXXXXXX XX   ",
    "  XXXXXXXXXXXX X XX   ",
    " XXXXXXXXXXXXX X XXX  ",
    " XXXXXXXXXXX X X XXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXOXX",
    "   XOXX         XXXXXX",
    "   XXX          X XXX ",
  ],
  [
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXXXX          ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  XXXXX ",
    "    XXXXXXXXXXXXXXXXX ",
    "    XXXXXXXXXX   XXX  ",
    "    XXXXXXXXXX   XXXX ",
    "    XXXXXXXXXX   XX XX",
    "   XXXXXXXXXXXXX XX   ",
    "  XXXXXXXXXXXX X XX   ",
    " XXXXXXXXXXXXX X XXX  ",
    " XXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXX ",
    "XXX X XXXXXXXXXXXXX XX",
    "XX X XXXXX X X XXXXX X",
    "X XXX XXX XXX XXX X XX",
    "   X X X X X X X XXX  ",
    "    X           X X X ",
  ],
  [
    "                      ",
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXXXX          ",
    "     XXXXXXX          ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXXX     X ",
    "    XXXXXXXXXXXXX  XX ",
    "    XXXXXXXXXX  X X X ",
    "    XXXXXXXXXXXXXXX X ",
    "    XXXXXXXXXX   X X X",
    "    XXXXXXXXXX    X X ",
    "    XXXXXXXXXX   X   X",
    "   XXXXXXXXXXXXX  X   ",
    "  XXXXXXXXXXXX X X X  ",
    "  X XXXXXXXXXX X XX X ",
    "   X XXXXXXX X X XXX  ",
    "  XXX XXX X X X X X XX",
    "   X X XXXXXXX X X X  ",
    "  X X X X XXX X   X   ",
    "     XXX X X X X X    ",
    "      XXX XXX X       ",
    "               X      ",
  ],
  [
    "                      ",
    "      XXXXX           ",
    "     XXXXXXX          ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "    XXXXXXXXX         ",
    "     XXXXXOX          ",
    "      XXXXXXX         ",
    "      XXXXXX          ",
    "     XXXXXXXX         ",
    "    XXXXXXXXXX   X    ",
    "    XXXXXXXXXX XXX X  ",
    "    XXXXXXXXXXX X X   ",
    "    XXXXXXXXXX X XX   ",
    "    XXXXXXXXXXX X X   ",
    "    XXXXXXXXXX X X    ",
    "    XXXXXXXXXX  X     ",
    "    XXXXXXXXXX X      ",
    "   XXXXXXXXXX X       ",
    "   X XXXXXXX X X      ",
    "    X X X X X  X      ",
    "     XXX XXX X X      ",
    "      X X X X X       ",
    "      XXXXXX X X      ",
    "      X X X X         ",
    "      X   X           ",
    "                      ",
    "                      ",
  ],
  [
    "                      ",
    "      XXXX            ",
    "     XXXXXX           ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXX X           ",
    "     XXXXXXX          ",
    "      XXXXX           ",
    "      XXXXX           ",
    "     XXXXXXXX         ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "   XXXXXXXXXXXX       ",
    "   XXXXXXXXXXXXX      ",
    "   XXXXXXXXXXX X      ",
    "   XXXXXXXXXXX X      ",
    "   XXXXXXXXXXX X      ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXX         ",
    "     XXXXXXX          ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      XX  XX          ",
  ],
  [
    "                      ",
    "      XXXX            ",
    "     XXXXXX           ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXX X           ",
    "     XXXXXXX          ",
    "      XXXXX           ",
    "      XXXXX           ",
    "     XXXXXXXX         ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "   XXXXXXXXXXXX       ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXX         ",
    "     XXXXXXX          ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      XX  XX          ",
  ],
];

const STAND = [
  [
    "                      ",
    "      XXXX            ",
    "     XXXXXX           ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXOX           ",
    "     XXXXXXX          ",
    "      XXXXX           ",
    "      XXXXX           ",
    "     XXXXXXXX         ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "   XXXXXXXXXXXX       ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXX         ",
    "     XXXXXXX          ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      XX  XX          ",
  ],
  [
    "                      ",
    "                      ",
    "      XXXX            ",
    "     XXXXXX           ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXXXX          ",
    "    XXXXXOX           ",
    "     XXXXXXX          ",
    "      XXXXX           ",
    "      XXXXX           ",
    "     XXXXXXXX         ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "   XXXXXXXXXXXX       ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX X      ",
    "  X XXXXXXXXXX        ",
    "    XXXXXXXXXX        ",
    "    XXXXXXXXX         ",
    "     XXXXXXX          ",
    "      X   X           ",
    "      X   X           ",
    "      X   X           ",
    "      XX  XX          ",
  ],
];

const SHOT_DIE = [
  [
    "                         ",
    "      XXXX               ",
    "     XXXXXX              ",
    "    XXXXXXXX             ",
    "    XXXXXXXX             ",
    "    XXXXXXXX             ",
    "    XXXXXOX              ",
    "     XXXXXXX             ",
    "      XXXXX              ",
    "      XXXXX              ",
    "     XXXXXXXX            ",
    "    XXXXXXXXXX           ",
    "    XXXXXXXXXX           ",
    "   XXXXXXXXXXX           ",
    "  X XXXXXXXXXX           ",
    "  X XXXXXXXXXX           ",
    "  X XXXXXXXXXX           ",
    "  X XXXXXXXXXX           ",
    "  X XXXXXXXXXX           ",
    "    XXXXXXXXXX           ",
    "    XXXXXXXXX            ",
    "     XXXXXXX             ",
    "      X   X              ",
    "      X   X              ",
    "      X   X              ",
    "      X   X              ",
    "      XX  XX             ",
  ],
  [
    "                         ",
    "        XXXX             ",
    "       XXXXXX            ",
    "      XXXXXXXX           ",
    "      XXXXXXXX           ",
    "      XXXXXXXX           ",
    "      XXXXXOX            ",
    "       XXXXXXX           ",
    "        XXXXX            ",
    "        XXXXX            ",
    "      XXXXXXXX           ",
    "     XXXXXXXXXX          ",
    "     XXXXXXXXXX          ",
    "    XXXXXXXXXXX          ",
    "   X XXXXXXXXXX          ",
    "  X  XXXXXXXXXX          ",
    "  X  XXXXXXXXXX          ",
    "  X  XXXXXXXXXX          ",
    "     XXXXXXXXXX          ",
    "     XXXXXXXXXX          ",
    "     XXXXXXXXX           ",
    "      XXXXXXX            ",
    "       X   X             ",
    "      X   X              ",
    "      X   X              ",
    "      X   X              ",
    "      XX  XX             ",
  ],
  [
    "                         ",
    "          XXXX           ",
    "         XXXXXX          ",
    "        XXXXXXXX         ",
    "        XXXXXXXX         ",
    "        XXXXXXXX         ",
    "        XXXXXOX          ",
    "         XXXXXXX         ",
    "          XXXXX          ",
    "          XXXXX          ",
    "      XXXXXXXXX          ",
    "     XXXXXXXXXXX         ",
    "     XXXXXXXXXXX         ",
    "     XXXXXXXXXXX         ",
    "    X XXXXXXXXXX         ",
    "   X XXXXXXXXXXX         ",
    "   X XXXXXXXXXXX         ",
    "   X XXXXXXXXXXX         ",
    "     XXXXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXX          ",
    "       XXXXXXX           ",
    "        X   X            ",
    "       X   X             ",
    "      X   X              ",
    "      X   X              ",
    "      XX  XX             ",
  ],
  [
    "                         ",
    "                         ",
    "             XXXXX       ",
    "            XXXXXXX      ",
    "           XXXXXXXX      ",
    "           XXXXXXXX      ",
    "           XXXXX X       ",
    "           XXXXXXXX      ",
    "            XXXXXX       ",
    "           XXXXXX        ",
    "       XXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "     XXXXXXXXXXX         ",
    "   XX XXXXXXXXXX         ",
    "  X  XXXXXXXXXXX         ",
    "  X X XXXXXXXXXX         ",
    "    X XXXXXXXXXX         ",
    "    X XXXXXXXXXX         ",
    "      XXXXXXXXX          ",
    "       XXXXXXX           ",
    "        X   X            ",
    "       X   X             ",
    "      X   X              ",
    "      X   X              ",
    "      XX  XX             ",
  ],
  [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                      XX ",
    "                     XXXX",
    "                   XXXXXX",
    "             XXXXXXXXXXXX",
    "          XXXXXXXXXXXXXXX",
    "        XXXXXXXXXXXXX XXX",
    "    XXXXXXXXXXXXXXXXXXXXX",
    "   X   XXXXXXXXXXX  X XX ",
    "  X  XXXXXXXXXXXXX       ",
    "    X  XXXXXXXXXX        ",
    "   X   XXXXXXXXXX        ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXXX         ",
    "      XXXXXXXXX          ",
    "       XXXXXXX           ",
    "        X   X            ",
    "       X   X             ",
    "      X   X              ",
    "      X   X              ",
    "      XX  XX             ",
  ],
  [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                     XXX ",
    "   XXX  XXXXXXXXX   XXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "   XXX XXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXX XXX",
    "       XXXXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXX  X XX ",
    "      XXXXXXXXXXXX       ",
    "      XXXXXXXXXXXX       ",
    "      XXXXXXXXXXXX       ",
    "      XXXXXXXXXXX        ",
    "       XXXXXXXXX         ",
    "       X    X            ",
    "      X    X             ",
    "     X    X              ",
    "      X    X             ",
    "                         ",
  ],
  [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "        XXXXXXXXX        ",
    "    XXXXXXXXXXXXXX   XXX ",
    "    X  XXXXXXXXXXX  XXXXX",
    "     XXXXXXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXXXXXX",
    "       XXXXXXXXXXXXXX XXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXX  X XX ",
    "      XXXXXXXXXXXX       ",
    "      XXXXXXXXXXX        ",
    "       XXXXXXXXX         ",
    "       X    X            ",
    "      X    X             ",
  ],
  [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                     XXX ",
    "        XXXXXXXXX   XXXXX",
    "      XXXXXXXXXXXXXXXXXXX",
    "     X XXXXXXXXXXXXXXXXXX",
    "      XXXXXXXXXXXXXXX XXX",
    "    X XXXXXXXXXXXXXXXXXXX",
    "    X XXXXXXXXXXXX  X XX ",
    "      XXXXXXXXXXXX       ",
    "     XXXXXXXXXXXXXX      ",
    "     XXXXXXXXXXXXXX      ",
    "     XXXXXXXXXXXXXX      ",
  ],
  [
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "                         ",
    "        XXXXXXXXX   XXXX ",
    "    XXXXXXXXXXXXXXXXXXXXX",
    "   XXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXXXXXX",
    "  XXXXXXXXXXXXXXXXXXX XXX",
    " XXXXXXXXXXXXXXXXXXXXXXXX",
    " XXXXXXXXXXXXXXXXXX X XXX",
  ],
];

export default {
  DRIVE,
  SCOOTER_BROKE,
  STAND,
  SHOT_DIE,
};
