const STAND = [
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX          ",
    "       XX XXX          ",
    "          X X          ",
    "          X  X         ",
    "          X  X         ",
    "          XX XX        ",
  ],
];

const WALK = [
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX          ",
    "       XX XXX          ",
    "          X X          ",
    "          X  X         ",
    "          X  X         ",
    "          XX XX        ",
  ],
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX          ",
    "       XX XXX          ",
    "          X X          ",
    "         X   X         ",
    "         X    X X      ",
    "         XX    X       ",
  ],
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX   X      ",
    "       XX XXXXXXX      ",
    "         X             ",
    "        X              ",
    "       X               ",
    "        X              ",
  ],
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX          ",
    "       XX XXX          ",
    "          X  X         ",
    "          X   X X      ",
    "          X    X       ",
    "          XX           ",
  ],
  [
    "         XXXXX         ",
    "        XXXXXXX        ",
    "       XXXXXXXX        ",
    "        XXXXOX         ",
    "         XXXXX         ",
    "         XXXXX         ",
    "          XXX          ",
    "           X           ",
    "        XXXXX    X     ",
    "       XXXXXXXXXXXX    ",
    "      XXXXXXX XX       ",
    "      XXXXXXXXX        ",
    "      XXXXXXX          ",
    "       XX XXX          ",
    "          X X          ",
    "         X  X          ",
    "         X  X          ",
    "         XX XX         ",
  ],
];

const WALK_DIAGONAL_AIM = [
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXXOX       ",
    "       XXXXX    X X",
    "       XXXXX     X ",
    "        XXX     X  ",
    "      XXXXX    X   ",
    "     XXXXXXXXXXX   ",
    "    XXXXXXXX   X   ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX      ",
    "          XXX      ",
    "          X X      ",
    "          X  X     ",
    "          X  X     ",
    "          XX XX    ",
  ],
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXXOX       ",
    "       XXXXX    X X",
    "       XXXXX     X ",
    "        XXX     X  ",
    "      XXXXX    X   ",
    "     XXXXXXXXXXX   ",
    "    XXXXXXXX   X   ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX      ",
    "          XXX      ",
    "          X  X     ",
    "         X    X    ",
    "         X     X X ",
    "         XX     X  ",
  ],
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXXOX       ",
    "       XXXXX    X X",
    "       XXXXX     X ",
    "        XXX     X  ",
    "      XXXXX    X   ",
    "     XXXXXXXXXXX   ",
    "    XXXXXXXX   X   ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX   X  ",
    "          XXXXXXX  ",
    "         X         ",
    "        X          ",
    "       X           ",
    "        X          ",
  ],
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXXOX       ",
    "       XXXXX    X X",
    "       XXXXX     X ",
    "        XXX     X  ",
    "      XXXXX    X   ",
    "     XXXXXXXXXXX   ",
    "    XXXXXXXX   X   ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX      ",
    "          XXX      ",
    "          X  X     ",
    "          X   X X  ",
    "          X    X   ",
    "          XX       ",
  ],
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXXOX       ",
    "       XXXXX    X X",
    "       XXXXX     X ",
    "        XXX     X  ",
    "      XXXXX    X   ",
    "     XXXXXXXXXXX   ",
    "    XXXXXXXX   X   ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX      ",
    "          XXX      ",
    "          X X      ",
    "         X  X      ",
    "         X  X      ",
    "         XX XX     ",
  ],
];

const STAND_AIM_UP = [
  [
    "       XXXXX       ",
    "      XXXXXXX      ",
    "     XXXXXXXX      ",
    "      XXXOXX       ",
    "       XXXXX  X    ",
    "       XXXXX XX    ",
    "        XXX   X    ",
    "      XXXXX  XX    ",
    "     XXXXXXXXXX    ",
    "    XXXXXXXX  X    ",
    "    XXXXXXXX XX    ",
    "    XXXXXXXXXX     ",
    "     XXX XXXX      ",
    "          XXX      ",
    "          X X      ",
    "         X  X      ",
    "         X  X      ",
    "         XX XX     ",
  ],
];

const DEAD = [
  [
    "                           ",
    "                X          ",
    "           X XX            ",
    "              X            ",
    "         XXXXXXX XX        ",
    "         X XXXXXX X        ",
    "        X X XXXXX X        ",
    "       XXX   X X X         ",
    "       X  XXXXX  X X       ",
    "         XXXXXXXXXXXX      ",
    "        XXXXXXX XX         ",
    "        XXXXXXXXX          ",
    "        XXXXXXX XX         ",
    "         XX XXX XX         ",
    "            XXXX           ",
    "            X  X X         ",
    "            XX X           ",
    "          XXXX XX          ",
  ],
  [
    "                           ",
    "         X         X       ",
    "                           ",
    "             X             ",
    "                       X   ",
    "            XXX            ",
    "        X X XXXXX X        ",
    "       XXX   X X X         ",
    "       X  XXXXX  X X       ",
    "       X XXXXXXXXXXXX      ",
    "      X XXXXXXXXXX  X      ",
    "      X XXXXXXXXXX  X      ",
    "      XXXXXXXXX   XX       ",
    "         XX XXX    X       ",
    "           XX X  X X       ",
    "           XXXXXXXX        ",
    "          XXXX XXXX        ",
    "            XXXXX          ",
  ],
  [
    "                           ",
    "                           ",
    "                    X      ",
    "      X             X      ",
    "                           ",
    "                           ",
    "        X  X               ",
    "       XX   XX         X   ",
    "          XXXXX  X X       ",
    "       X XXXXXXXXXXXX      ",
    "      X XXXXXXXXXX  X      ",
    "      X XXXXXXXXXX  X      ",
    "      XXXXXXXXX   XX       ",
    "         XX XXX X  X       ",
    "        XX XX XX X X       ",
    "       XXXXXXXXX    X      ",
    "          XXXXXXXXXXX      ",
    "            XXXXX   X      ",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "     X             X       ",
    "                           ",
    "           XXXXX      X    ",
    "      X XXXXXXXXXX         ",
    "      X XXXXXXXXXX  X      ",
    "      XXXXXXXXX  XXX       ",
    "         XX XXXXXXXX       ",
    "       XXX XXXX XX X       ",
    "       X  XXXXXX XX X      ",
    "       XXXX XXXXXXXXX      ",
    "        XXXXXXXXX  X       ",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "          XXX        X     ",
    "            XX             ",
    "    X                      ",
    "      XXXXXXXXX  XXX  X    ",
    "      X  XX XXXXXXXX X     ",
    "     X XXX XXXX XX X  X    ",
    "    X  X    XXXXXXX X XX   ",
    "    XX XXXXXXXXXX XXX   X  ",
    "      X  XXXXXXXXX X X  X  ",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "           XXXX            ",
    "            XXXX           ",
    "    XX XXX XXXX XX X X     ",
    "    X  X  XXXXXXXX X XX X  ",
    "    XX XXXXXXXXXXXXXX  X X ",
    "XXXX  X   XXXXXXX  X X  X X",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "            XXX            ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "            XXX            ",
    "            XXX            ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
  [
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "                           ",
    "             X             ",
    "            XXX            ",
    "            XXX            ",
    "          XXXXXXX          ",
    "         XXXXXXXXX         ",
    "          XXXXXXX          ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "            XXX            ",
    "    XXXXXXXXXXXXXXXXXXXXX  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  ],
];

export default {
  STAND,
  WALK,
  WALK_DIAGONAL_AIM,
  STAND_AIM_UP,
  DEAD,
};
