const arrow_up = [
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "            X            ",
  "           XXX           ",
  "          XXXXX          ",
  "         XXXXXXX         ",
  "        XXXXXXXXX        ",
  "       XXXXXXXXXXX       ",
  "      XXXXXXXXXXXXX      ",
  "     XXXXXXXXXXXXXXX     ",
  "    XXXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXXX    ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "         XXXXXXX         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
];

const arrow_left = [
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "            XX           ",
  "           XXX           ",
  "          XXXX           ",
  "         XXXXX           ",
  "        XXXXXX           ",
  "       XXXXXXXXXXXXXX    ",
  "      XXXXXXXXXXXXXXX    ",
  "     XXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXXX    ",
  "     XXXXXXXXXXXXXXXX    ",
  "      XXXXXXXXXXXXXXX    ",
  "       XXXXXXXXXXXXXX    ",
  "        XXXXXX           ",
  "         XXXXX           ",
  "          XXXX           ",
  "           XXX           ",
  "            XX           ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
];

const arrow_right = [
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "           XX            ",
  "           XXX           ",
  "           XXXX          ",
  "           XXXXX         ",
  "           XXXXXX        ",
  "    XXXXXXXXXXXXXX       ",
  "    XXXXXXXXXXXXXXX      ",
  "    XXXXXXXXXXXXXXXX     ",
  "    XXXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXX     ",
  "    XXXXXXXXXXXXXXX      ",
  "    XXXXXXXXXXXXXX       ",
  "           XXXXXX        ",
  "           XXXXX         ",
  "           XXXX          ",
  "           XXX           ",
  "           XX            ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
];

const bullet = [
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "    X  XXXXXXXXXX        ",
  "    XXXXXXXXXXXXXXXX     ",
  "    XXXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXXX    ",
  "    XXXXXXXXXXXXXXXX     ",
  "    X  XXXXXXXXXX        ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
  "                         ",
];

export default {
  arrow_up,
  arrow_left,
  arrow_right,
  bullet,
};
